name       : vorta
version    : 0.6.24
release    : 6
source     :
    - https://github.com/borgbase/vorta/archive/v0.6.24.tar.gz : 36ad9592478d6c486ab12e399f8966fd034f94be111457d7165d3828a24e7efe
license    : GPL-3.0-only
component  : desktop
summary    : Vorta Backup Client
description: |
    Desktop Backup Client for Borg
builddeps  :
    - pytest-runner
    - python-setuptools-git
rundeps    :
    - borg
    - python-appdirs
    - python-apscheduler
    - python-dateutil
    - python-keyring
    - python-paramiko
    - python-peewee
    - python-psutil
    - python-qdarkstyle
    - python3-qt5
setup      : |
    mkdir -p .soltmp/icons
    mv src/vorta/assets/metadata .soltmp
build      : |
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.desktop $installdir/usr/share/applications/com.borgbase.Vorta.desktop
    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.appdata.xml $installdir/usr/share/metainfo/com.borgbase.Vorta.appdata.xml
    install -Dm00644 src/vorta/assets/icons/scalable/com.borgbase.Vorta.svg $installdir/usr/share/icons/hicolor/scalable/apps/com.borgbase.Vorta.svg
