name       : vorta
version    : 0.7.5
release    : 11
source     :
    - https://github.com/borgbase/vorta/archive/v0.7.5.tar.gz : 1098d37c958fcc80c5a72f5f81023d6541cccb9c20cd27a791a3cf21a31e2603
license    : GPL-3.0-only
component  : desktop
summary    : Vorta Backup Client
description: |
    Desktop Backup Client for Borg
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pytest-runner
    - python-setuptools-git
rundeps    :
    - borg
    - python-appdirs
    - python-apscheduler
    - python-dateutil
    - python-paramiko
    - python-peewee
    - python-psutil
    - python-secretstorage
    - python3-qt5
setup      : |
    mkdir -p .soltmp/icons
    mv src/vorta/assets/metadata .soltmp
build      : |
    %make translations-to-qm
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.desktop $installdir/usr/share/applications/com.borgbase.Vorta.desktop
    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.appdata.xml $installdir/usr/share/metainfo/com.borgbase.Vorta.appdata.xml
    install -Dm00644 $pkgfiles/com.borgbase.Vorta.svg $installdir/usr/share/icons/hicolor/scalable/apps/com.borgbase.Vorta.svg
