name       : vorta
version    : 0.8.4
release    : 20
source     :
    - https://github.com/borgbase/vorta/archive/refs/tags/v0.8.4.tar.gz : 9396915819d6ccb204e4321b8fe482fd2421563a09fa0daab9b2e982d2b9d50b
license    : GPL-3.0-only
component  : desktop
summary    : Vorta Backup Client
description: |
    Desktop Backup Client for Borg
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pytest-runner
    - python-setuptools-git
rundeps    :
    - borg
    - python-appdirs
    - python-dateutil
    - python-paramiko
    - python-peewee
    - python-psutil
    - python-secretstorage
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-.desktop-file-path-in-autostart.py.patch

    mkdir -p .soltmp/icons
    mv src/vorta/assets/metadata .soltmp
build      : |
    %make translations-to-qm
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.desktop $installdir/usr/share/applications/com.borgbase.Vorta.desktop
    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.appdata.xml $installdir/usr/share/metainfo/com.borgbase.Vorta.appdata.xml
    install -Dm00644 $pkgfiles/com.borgbase.Vorta.svg $installdir/usr/share/icons/hicolor/scalable/apps/com.borgbase.Vorta.svg
