name       : vorta
version    : 0.6.20
release    : 2
source     :
    - https://github.com/borgbase/vorta/archive/v0.6.20.tar.gz : a9ff638c626731207c2bc07f6239c69c91429bd4a0db6fb4126a8fc954481199
license    : GPL-3.0-only
component  : desktop
summary    : Vorta Backup Client
description: |
    Desktop Backup Client for Borg
builddeps  :
    - pytest-runner
    - python-setuptools-git
rundeps    :
    - borg
    - python-appdirs
    - python-apscheduler
    - python-dateutil
    - python-keyring
    - python-paramiko
    - python-peewee
    - python-psutil
    - python-qdarkstyle
    - python3-qt5
setup      : |
    mkdir -p .soltmp/icons
    for i in 24 32 48 64 128 256 512; do
        mv src/vorta/assets/icons/${i}x${i} .soltmp/icons
    done
    mv src/vorta/assets/metadata .soltmp
    
build      : |
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 .soltmp/metadata/com.borgbase.vorta.desktop $installdir/usr/share/applications/com.borgbase.vorta.desktop
    install -Dm00644 .soltmp/metadata/com.borgbase.vorta.appdata.xml $installdir/usr/share/metainfo/com.borgbase.vorta.appdata.xml

    for i in 24 32 48 64 128 256 512; do
        install -Dm00644 .soltmp/icons/${i}x${i}/com.borgbase.vorta.png $installdir/usr/share/icons/hicolor/${i}x${i}/apps/com.borgbase.vorta.png
    done
