name       : vorta
version    : 0.6.23
release    : 5
source     :
    - https://github.com/borgbase/vorta/archive/v0.6.23.tar.gz : 51304e49ff18ac4957fa7d24be20ff79de6215fa163615a798c571bff64b6d2a
license    : GPL-3.0-only
component  : desktop
summary    : Vorta Backup Client
description: |
    Desktop Backup Client for Borg
builddeps  :
    - pytest-runner
    - python-setuptools-git
rundeps    :
    - borg
    - python-appdirs
    - python-apscheduler
    - python-dateutil
    - python-keyring
    - python-paramiko
    - python-peewee
    - python-psutil
    - python-qdarkstyle
    - python3-qt5
setup      : |
    mkdir -p .soltmp/icons
    for i in 24 32 48 64 128 256 512; do
        mv src/vorta/assets/icons/${i}x${i} .soltmp/icons
    done
    mv src/vorta/assets/metadata .soltmp

build      : |
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.desktop $installdir/usr/share/applications/com.borgbase.Vorta.desktop
    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.appdata.xml $installdir/usr/share/metainfo/com.borgbase.Vorta.appdata.xml

    for i in 24 32 48 64 128 256 512; do
        install -Dm00644 .soltmp/icons/${i}x${i}/com.borgbase.Vorta.png $installdir/usr/share/icons/hicolor/${i}x${i}/apps/com.borgbase.Vorta.png
    done
