name       : vorta
version    : 0.8.12
release    : 23
source     :
    - https://github.com/borgbase/vorta/archive/refs/tags/v0.8.12.tar.gz : 697a1d6f6f93b1b2447c7f19cf250d24d72e2f784e62c54287d9ee39cac59f38
homepage   : https://vorta.borgbase.com/
license    : GPL-3.0-only
component  : desktop
summary    : A Desktop Client for Borg Backup
description: |
    Vorta is a backup client for macOS and Linux desktops. It integrates the mighty Borg Backup with your favorite desktop environment to protect your data from disk failure, ransomware and theft.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - python-setuptools-git
rundeps    :
    - borg
    - python-appdirs
    - python-dateutil
    - python-paramiko
    - python-peewee
    - python-platformdirs
    - python-psutil
    - python-secretstorage
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-.desktop-file-path-in-autostart.py.patch

    mkdir -p .soltmp/icons
    mv src/vorta/assets/metadata .soltmp
build      : |
    %make translations-to-qm
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.desktop $installdir/usr/share/applications/com.borgbase.Vorta.desktop
    install -Dm00644 .soltmp/metadata/com.borgbase.Vorta.appdata.xml $installdir/usr/share/metainfo/com.borgbase.Vorta.appdata.xml
    install -Dm00644 $pkgfiles/com.borgbase.Vorta.svg $installdir/usr/share/icons/hicolor/scalable/apps/com.borgbase.Vorta.svg
